# AI/Machine Learning Training

# A Program by Dhaarini AI-Tech Research Academy

## Learning Objectives

By the end of this session, you will be able to:

1.   understand the fundamentals of machine learning

1.   Types of Algorithms for Machine Learning

2.  understanding how Train/Test Split is implemented.

2.  Types and Concepts of Linear Regression Analysis


1.   Real-World Use Case: Predicting Salary



### Introduction

**Machine Learning (ML)** is a subfield of Artificial Intelligence that allows systems to learn from data, discover patterns, and make judgments with no human involvement.

**Machine Learning use cases:**

Real-world applications powered by machine learning include detecting cancers in brain scans, automatically classifying news items, flagging objectionable comments, summarizing documents, and building chatbots or personal assistants.  Other practical applications include detecting credit card fraud, enabling voice commands in apps, developing intelligent game bots, recommending things, predicting house prices, identifying spam, recognizing faces, forecasting trends, and diagnosing diseases.



**Machine Learning Workflow**

*  Data Gathering → Collect relevant information

*   Data Preparation → Refine and structure data

*   Data Preparation → Refine and structure data
*  Model Building → Train algorithm on data

*   Model Testing → Validate performance

*   Implementation → Deploy for real-world use






### Understanding Train/Test Split in Machine Learning

 Imagine training a student using only past exam papers, then testing them on the exact same papers. They'd score perfectly! But on a new exam, they might fail because they memorized answers rather than learning concepts.


Similarly, if we train a machine learning model on data and test it on the same data, we can't tell if the model learned real patterns or just memorized the examples. This is called overfitting.

By dividing data into distinct training and testing sections, we ensure an honest evaluation of how well the model performs on completely new, unseen data.

1. **Training Dataset**
This is the data your algorithm learns from. The model studies patterns, relationships, and features in this dataset to adjust its internal parameters.
Purpose: Teaching the model

2. **Test Dataset**
This is all new data for the model.  You use it to see how well your model adapts to new scenarios.
Purpose: Final performance evaluation

3. **Validation Dataset**
During training, you use this separate set to monitor how well the model is performing on unseen data. It helps you catch overfitting early and tune parameters without using the final test set.
Purpose: Monitoring during training and hyperparameter tuning

**Common Split Ratios**

The exact percentages depend on your situation and available data:

80% train / 20% test: Standard choice for most projects

70% train / 30% test: Used when you have abundant data

75% train / 25% test: Common middle ground

60% train / 20% validation / 20% test: When fine-tuning parameters






### Importing required packages

In [13]:
# Importing Standard Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Importing sklearn Libraries
from sklearn import datasets
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split, learning_curve
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

### Let us use a small dataset to understand how to implement a train and test split

#### Creating a simple dataset to work with

In [14]:
# Student study hours and sleep hours (X) vs exam pass/fail (y)
# Each row: [study_hours, sleep_hours]
X = np.array([
    [2, 8],    #study #sleep
    [3, 7],
    [5, 6],
    [1, 5],
    [6, 7],
    [4, 4],
    [2, 3],
    [7, 6],
    [6, 8],
    [3, 5],
    [8, 7],
    [3, 4]
])

# Exam results: 0 = Failed, 1 = Passed
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [15]:
print(X)

[[2 8]
 [3 7]
 [5 6]
 [1 5]
 [6 7]
 [4 4]
 [2 3]
 [7 6]
 [6 8]
 [3 5]
 [8 7]
 [3 4]]


In [16]:
print(y)

[0 1 1 0 1 0 0 1 1 0 1 0]


#### Splitting input and output datasets

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=4, random_state=4)

In [18]:
X_train

array([[6, 8],
       [5, 6],
       [3, 4],
       [2, 8],
       [3, 7],
       [4, 4],
       [7, 6],
       [8, 7]])

In [19]:
X_test

array([[1, 5],
       [6, 7],
       [2, 3],
       [3, 5]])

In [20]:
y_train

array([1, 1, 0, 0, 1, 0, 1, 1])

In [21]:
y_test

array([0, 1, 0, 0])

**Linear Regression**

A straight-line equation of the following form is used in the statistical technique known as linear regression to represent the linear connection between a dependent variable (the target) and one or more independent variables (predictors):

### 𝑦=𝑚𝑥+𝑐

Where:

y = predicted result

x = the input feature.

m is the slope. (Display the amount that y changes as x changes.)

C is equal to the intercept (y value when x = 0)

### Gain knowledge about least squares

**Least Squares** method is a statistical procedure to find the best fit for a set of data points by minimizing the sum of the offsets or residuals of points from the plotted curve.

**Calculate Line Of Best Fit**

A more accurate way of finding the line of best fit is the least square method.

Use the following steps to find the equation of line of best fit for a set of ordered pairs $(x_1,y_1),(x_2,y_2),...(x_n,y_n)$.

**Step 1:** Calculate the slope ‘m’ by using the following formula:

$$m = \frac{\sum \left ( x-\bar{x} \right )* \left ( y-\bar{y} \right )}{\sum \left ( x-\bar{x} \right )^{2}}$$


**Step 2:** Compute the y -intercept of the line by using the formula:

$$c = y - mx$$

**Step 3:** Substitute the values in the final equation

$$y = mx + c$$

* y: dependent variable
* m: the slope of the line
* x: independent variable
* c: y-intercept


As an example, we will try to find the least squares regression line for the below data set:

\begin{array} {|r|r|}\hline Hours Spent & Grade \\\hline 6 & 82 \\ \hline 10 & 88 \\ \hline 2 & 56 \\ \hline 4 & 64 \\ \hline 6 & 77 \\ \hline 7 & 92 \\ \hline 0 & 23 \\ \hline 1 & 41 \\ \hline 8 & 80 \\ \hline 5 & 59 \\ \hline 3 & 47 \\ \hline  \end{array}

$x$ = HoursSpent

$y$ = Grade

$\bar{x}$ = 4.72

$\bar{y}$ = 64.45


\begin{array} {|r|r|}\hline Hours Spent & Grade &  x - \bar{x}  & y - \bar{y} & (x - \bar{x})*(y - \bar{y}) \\ \hline 6 & 82 & 1.27 & 17.55 & 22.33 \\ \hline 10 & 88 & 5.27 & 23.55 & 124.15 \\ \hline 2 & 56 & -2.73 & -8.45 & 23.06 \\ \hline 4 & 64 & -0.73 & -0.45 & 0.33 \\ \hline 6 & 77 & 1.27 & 12.55 & 15.97 \\ \hline 7 & 92 & 2.27 & 27.55 & 62.60 \\ \hline 0 & 23 & -4.73 & -41.45 & 195.97 \\ \hline 1 & 41 & -3.73 & -23.42 & 87.42 \\ \hline 8 & 80 & 3.27 & 15.55 & 50.88 \\ \hline 5 & 59 & 0.27 & -5.45 & -1.49 \\ \hline 3 & 47 & -1.73 & -17.45 & 30.15 \\ \hline  \end{array}


$$\sum \left ( x-\bar{x} \right )* \left ( y-\bar{y} \right ) = 611.36$$

$$\sum \left ( x-\bar{x} \right )^{2} = 94.18$$

$$m = \frac{611.36}{94.18}$$

$$m = 6.49$$

**Calculate the intercept:**

$$c = y - mx$$

$$c = 64.45-(6.49*4.72)$$

$$c = 64.45 – 30.63$$

$$c = 30.18$$

Now that we have all the values to fit into the equation. If we want to know the predicted grade of someone who spends 2.35 hours on their essay, all we need to do is substitute that in for X.

$$y =  (6.49 * X) + 30.18 $$

$$y = (6.49 * 2.35) + 30.18$$

$$y = 45.43$$










### Example: Machine Learning Workflow using Linear-Regression with Salary Prediction Dataset

#### Dataset

In this example, we will be using the “Salary Prediction” dataset.


Problem statement: Salary against years of exp.

#### Loading Data

In [ ]:
# Read data
sal = pd.read_csv("Salary.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/Salary.csv'

Displaying Dataframe

In [ ]:
sal.head()

#### Exploring the dataset

In [ ]:
# print names of the features
print(sal.columns)

In [ ]:
# generating descriptive statistics that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding NaN values.
sal.describe()

In [ ]:
# summary of the DataFrame
sal.info()

#### Checking for Missing values

In [ ]:
sal.isna().sum()

In [ ]:
pip install pandas-profiling

In [ ]:
pip install ydata-profiling


In [ ]:
from ydata_profiling import ProfileReport
Pf=ProfileReport(sal)

In [ ]:
Pf.to_notebook_iframe()

In [ ]:
# Pairplot
plt.style.use('ggplot')
sns.pairplot(sal)

In [ ]:
# Heatmap
plt.figure(figsize=(8, 8))
sns.heatmap(sal.corr(), annot=True, linewidth=0.5, center=0)
plt.show()

### Modeling and Prediction (Linear Regression)

In [ ]:
sal.head()

In [ ]:
# Datatypes of all features
sal.dtypes

In [ ]:
# Pridiction features
X = sal[['YearsExperience']]
# Target feature
y = sal['Salary']
X.head()

In [ ]:
# Splitting the Dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.33, random_state= 101)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
y_train

In [ ]:
y_test

In [ ]:
# Instantiating LinearRegression() Model
lr = LinearRegression()

In [ ]:
# Training/Fitting the Model
lr.fit(X_train, y_train)

Testing

In [ ]:
# Making Predictions
pred = lr.predict(X_test)

In [ ]:
print("coefficient is : " ,lr.coef_)
print("intercept is :" ,lr.intercept_)

In [ ]:
# Evaluating Model's Performance
print('Mean Absolute Error:', mean_absolute_error(y_test, pred))
print('Mean Squared Error:', mean_squared_error(y_test, pred))
print('Mean Root Squared Error:', np.sqrt(mean_squared_error(y_test, pred)))
print('Coefficient of Determination:', r2_score(y_test, pred))

Predicting the value

In [ ]:
lr.predict([[2.2]])

In [ ]:
pred = lr.predict(X_test)
print('Predicted salary:', pred[3])
print('Actual salary:', y_test.values[3])

In [ ]:
plt.scatter(X, y, color='blue')
plt.plot(X, lr.predict(X), color='red')  # Best fit line
plt.title('Linear Regression Line')
plt.xlabel('YearsExperience')
plt.ylabel('Salary')
plt.show()

# Multiple Linear Regression

In [ ]:
# Create Dataset
data = {
    'Area_sqft': [1000, 1500, 2000, 2500, 3000],
    'Bedrooms': [2, 3, 3, 4, 4],
    'Price': [300000, 400000, 450000, 500000, 600000]
}
df2 = pd.DataFrame(data)
df2


In [ ]:
X = df2[['Area_sqft','Bedrooms']]
y = df2['Price']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X, y)

In [ ]:
new_house = pd.DataFrame({'Area_sqft': [2000], 'Bedrooms': [3]})
predicted_price = model.predict(new_house)
print("Predicted House Price:", predicted_price[0])

#### Polynomial Features

characteristics that are produced by raising preexisting characteristics to an exponent are known as polynomial features.

A polynomial feature, for instance, would be the creation of a new feature (column) with values determined by squaring the values in $X$, such as $X^2$, if a dataset had a single input feature $X$. Each input variable in the dataset can be modified by repeating this method. Additionally, the degree-2 polynomial features of a two-dimensional input sample of the type $[a, b]$ are $[1, a, b, a^2, ab, b^2]$.

Polynomial features are therefore a form of feature engineering, which is the process of developing new input features based on preexisting features.The polynomial's "degree" determines how many features are added; for example, a degree of three adds two new variables for every input variable. Usually, a small degree, like two or three, is employed.

In [ ]:
def PolynomialRegression(degree=2, **kwargs):
    return make_pipeline(PolynomialFeatures(degree), LinearRegression(**kwargs))   # using a pipeline to string these operations together

In [ ]:
def make_data(N, err=1.0, rseed=1):
    # randomly sample the data
    rng = np.random.RandomState(rseed)
    X = rng.rand(N, 1) ** 2
    y = 10 - 1. / (X.ravel() + 0.1)
    if err > 0:
        y += err * rng.randn(N)
    return X, y

X, y = make_data(40)

In [ ]:
# learning curve for generated dataset with a second-order polynomial model and a ninth-order polynomial

fig, ax = plt.subplots(1, 2, figsize=(16, 6))
fig.subplots_adjust(left=0.0625, right=0.95, wspace=0.1)

for i, degree in enumerate([2, 7]):
    N, train_lc, val_lc = learning_curve(PolynomialRegression(degree),
                                         X, y, cv=7,
                                         train_sizes=np.linspace(0.3, 1, 25))

    ax[i].plot(N, np.mean(train_lc, 1), color='blue', label='training score')
    ax[i].plot(N, np.mean(val_lc, 1), color='red', label='validation score')
    ax[i].hlines(np.mean([train_lc[-1], val_lc[-1]]), N[0], N[-1],
                 color='gray', linestyle='dashed')

    ax[i].set_ylim(0, 1)
    ax[i].set_xlim(N[0], N[-1])
    ax[i].set_xlabel('training size')
    ax[i].set_ylabel('score')
    ax[i].set_title('degree = {0}'.format(degree), size=14)
    ax[i].legend(loc='best')

### Regularized Linear Models

Regularizing the model, or constraining it, is a smart technique to lessen overfitting because it will be more difficult for the model to overfit the data if it has fewer degrees of freedom.

Regularization for a linear model is usually accomplished by limiting the model's weights.

There are three methods for limiting the weights:

1. Ridge Regression

2. Regression Lasso

3. The Elastic Net

#### **Ridge regression**

**Ridge regression** or **Tikhonov regularization** is the regularization technique that performs L2 regularization. It modifies the loss function by adding the penalty (shrinkage quantity) equivalent to the square of the magnitude of coefficients.

- **sklearn.linear_model.Ridge** is the module used to solve a regression model where the loss function is the linear least squares function and regularization is L2.

#### Ridge Regression with Scikit-Learn

In [ ]:
n_samples, n_features = 15, 10
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)

rdg = linear_model.Ridge(alpha = 0.5)                  # instantiate Ridge regressor
rdg.fit(X, y)
rdg.score(X,y)

#### **LASSO (Least Absolute Shrinkage and Selection Operator)**

LASSO is the regularisation technique that performs L1 regularisation. It modifies the loss function by adding the penalty (shrinkage quantity) equivalent to the summation of the absolute value of coefficients.

 - **sklearn.linear_model.Lasso** is a linear model, with an added regularisation term, used to estimate sparse coefficients.


#### Lasso Regression with Scikit-Learn

In [ ]:
# uses coordinate descent as the algorithm to fit the coefficients

Lreg = linear_model.Lasso(alpha = 0.5)
Lreg.fit([[0,0], [1, 1], [2, 2]], [0, 1, 2])

The model can forecast new values in the following ways after it has been fitted:

In [ ]:
Lreg.predict([[0,1]])

In [ ]:
Lreg.coef_

In [ ]:
Lreg.intercept_

In [ ]:
#Calculating number of iterations
Lreg.n_iter_

#### Elastic-Net Regression

A regularized regression technique called **Elastic-Net** linearly integrates the L1 and L2 penalties of the Lasso and Ridge regression techniques.

In [ ]:
ENreg = linear_model.ElasticNet(alpha = 0.5,random_state = 0)
ENreg.fit([[0,0], [1, 1], [2, 2]], [0, 1, 2])

In [ ]:
ENreg.predict([[0,1]])

In [ ]:
ENreg.coef_